# Generated by Django 2.2.12 on 2020-04-20 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('social_django', '0008_partial_timestamp'),
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='members',
            field=models.ManyToManyField(related_name='teams', to='social_django.UserSocialAuth'),
        ),
    ]
