# Generated by Django 2.2.12 on 2020-04-24 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_team_manager'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='manager',
        ),
        migrations.RemoveField(
            model_name='team',
            name='members',
        ),
    ]
