# Generated by Django 2.2.12 on 2020-05-03 02:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0006_auto_20200501_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='issue',
            name='link_type',
            field=models.CharField(blank=True, choices=[('Blocks', 'Blocks another issue'), ('Is blocked by', 'Is blocked by other issue'), ('Relates to', 'Relates to another issue')], default='Blocks', max_length=50),
        ),
        migrations.AlterField(
            model_name='issue',
            name='assignee',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='assigned_to', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='issue',
            name='description',
            field=models.TextField(blank=True, max_length=2000),
        ),
    ]
