# Generated by Django 2.2.12 on 2020-05-04 02:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0007_auto_20200503_0253'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='issue',
            name='link_type',
        ),
        migrations.RemoveField(
            model_name='issue',
            name='linked_to',
        ),
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('link_type', models.CharField(blank=True, choices=[('Blocks', 'Blocks'), ('Blocked By', 'Blocked By'), ('Relates To', 'Relates To')], max_length=50)),
                ('link_ref', models.ManyToManyField(related_name='linked_to', to='issues.Issue')),
            ],
        ),
    ]
