# Generated by Django 2.2.12 on 2020-07-08 19:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0009_auto_20200504_0257'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='link_ref',
        ),
        migrations.AddField(
            model_name='link',
            name='child_issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='linked_by', to='issues.Issue'),
        ),
        migrations.AddField(
            model_name='link',
            name='parent_issue',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='links_to', to='issues.Issue'),
        ),
    ]
