# Generated by Django 2.2.12 on 2020-07-08 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('issues', '0010_auto_20200708_1947'),
    ]

    operations = [
        migrations.RenameField(
            model_name='link',
            old_name='link_type',
            new_name='kind',
        ),
    ]
