# Generated by Django 2.2.12 on 2020-04-17 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpicture',
            name='picture',
            field=models.ImageField(height_field=500, upload_to='media', width_field=500),
        ),
    ]
