# Generated by Django 2.2.12 on 2020-04-17 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20200417_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userpicture',
            name='picture',
            field=models.ImageField(upload_to='media'),
        ),
    ]
